"""initial schema

Revision ID: 08b1b40ac803
Revises: 
Create Date: 2026-09-08 12:22:55.189822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08b1b40ac803'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('detections', sa.Column('uncertainty', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'uncertainty')
    op.drop_column('detections', 'longitude')
    op.drop_column('detections', 'latitude')
    # ### end Alembic commands ###
