"""add survey progress

Revision ID: 1776a8303597
Revises: 08b1b40ac803
Create Date: 2026-09-08 12:49:33.622746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1776a8303597'
down_revision: Union[str, Sequence[str], None] = '08b1b40ac803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('progress', sa.Integer(), nullable=True))
    op.add_column('surveys', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('surveys', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surveys', 'updated_at')
    op.drop_column('surveys', 'created_at')
    op.drop_column('surveys', 'progress')
    # ### end Alembic commands ###
