import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Check, CircleHelp, Image as ImageIcon, X } from "lucide-react";
import { mockSurvey } from "../services/api";
import Badge from "../components/Badge";
import SonarViewer from "../components/SonarViewer";

export default function AnomalyDetails() {
  const { anomalyId } = useParams(); const item = mockSurvey.detections.find(d=>d.id===anomalyId) || mockSurvey.detections[0]; const [status,setStatus]=useState(item.status);
  return <div><Link className="back-link" to={`/surveys/${mockSurvey.id}`}><ArrowLeft size={16}/> Back to survey</Link><div className="page-heading"><div><span className="eyebrow">ANOMALY REVIEW</span><h1>{item.type}</h1><p>{item.id} · Detected by AI model</p></div><Badge tone={status==="Confirmed"?"success":status==="Rejected"?"danger":"warning"}>{status}</Badge></div><div className="anomaly-layout"><section className="panel"><div className="panel-title"><h3>Detection preview</h3><span className="muted">Bounding box: {item.confidence}% confidence</span></div><SonarViewer detections={[item]}/></section><section className="panel"><div className="panel-title"><h3>Review decision</h3><span className="muted">Update the status after inspection</span></div><div className="review-options"><button className={status==="Confirmed"?"selected success-border":""} onClick={()=>setStatus("Confirmed")}><Check size={20}/><span><strong>Confirm</strong><small>This is a valid anomaly.</small></span></button><button className={status==="Rejected"?"selected danger-border":""} onClick={()=>setStatus("Rejected")}><X size={20}/><span><strong>Reject</strong><small>This is a false positive.</small></span></button><button className={status==="Uncertain"?"selected warning-border":""} onClick={()=>setStatus("Uncertain")}><CircleHelp size={20}/><span><strong>Uncertain</strong><small>Needs further investigation.</small></span></button></div><div className="detail-list"><div><span>Object class</span><strong>{item.type}</strong></div><div><span>Confidence</span><strong>{item.confidence}%</strong></div><div><span>Priority</span><strong>{item.priority}</strong></div><div><span>Coordinates</span><strong>Relative X {item.x} · Y {item.y}</strong></div></div><button className="primary-btn full" onClick={()=>alert(`Status saved as ${status}`)}>Save review decision</button></section></div></div>;
}